site_name: Nougaro Documentation
site_author: Jean Dubois

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
